name: Draft PDF

on:
  push:
    paths:
      - 'manuscript/**'
      - 'images/**'
      - '.github/workflows/draft-pdf.yml'
  # This adds the manual "Run workflow" button
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: manuscript/paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: manuscript/paper.pdf

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: 'manuscript/paper.pdf'
